<?php include 'includes/header.php'; ?>
<?php include 'components/hero.php'; ?>
<?php include 'components/hero-info.php'; ?>
<?php include 'components/overview.php'; ?>
<?php include 'components/highlights.php'; ?>
<?php include 'components/amenities.php'; ?>
<?php include 'components/floor-plan.php'; ?>
<?php include 'components/location.php'; ?>
<?php include 'components/projects.php'; ?>
<?php include 'includes/footer.php'; ?>
